### ISSUE TITLE
Running ospgrillage 0.1.1 on Windows 10 with Python 3.9

### ISSUE THREAD

**Issue by DougAJ4** [MonashSmartStructures/ospgrillage#16]
Running ospgrillage 0.1.1 on Windows 10 with Python 3.9
With the default installation the command 
import ospgrillage as og
returns a message that Python 3.8 is required.

I tried modifying the __init__.py file in the openseespywin folder to:
if sys.version_info[0] == 3 and sys.version_info[1] >= 8: 

This then returns the following message:
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import ospgrillage as og
Traceback (most recent call last):
  File "d:\Users\dougj\Miniconda64\lib\site-packages\openseespywin\__init__.py", line 20, in <module>
    from openseespywin.opensees import *
ImportError: DLL load failed while importing opensees: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Users\dougj\Miniconda64\lib\site-packages\openseespy\opensees\__init__.py", line 19, in <module>
    from openseespywin.opensees import *
  File "d:\Users\dougj\Miniconda64\lib\site-packages\openseespywin\__init__.py", line 23, in <module>
    raise RuntimeError('Failed to import openseespy on Windows.')
RuntimeError: Failed to import openseespy on Windows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Users\dougj\Miniconda64\lib\site-packages\ospgrillage\__init__.py", line 6, in <module>
    from ospgrillage.osp_grillage import *
  File "d:\Users\dougj\Miniconda64\lib\site-packages\ospgrillage\osp_grillage.py", line 11, in <module>
    import openseespy.opensees as ops
  File "d:\Users\dougj\Miniconda64\lib\site-packages\openseespy\opensees\__init__.py", line 23, in <module>
    raise RuntimeError('Failed to import openseespy on Windows.')
RuntimeError: Failed to import openseespy on Windows.
>>>

**Comment by justinngan92** [comment]
Hi Doug,

This is an issue with OpenSees requiring version 3.8 ([see here](https://github.com/zhuminjie/OpenSeesPy/issues/56)).

The workaround is to create a virtual environment of py 3.8. You can use [virtualenv](https://virtualenv.pypa.io/en/latest/user_guide.html) to make a 3.8 venv.

Here's how-to. In cmd:
```
 python -m virtualenv ospg --python=python3.8
```
This creates a virtual env named "ospg" with python ver 3.8. To switch to it do:
```
ospg\scripts\activate
```

**Comment by DougAJ4** [comment]
Thanks justin,
I couldn't get virtualenv to work, perhaps because I had installed Python with miniconda, but I finally got it to work using Condaenv:
Install Python 3.8 using miniconda, ensuring it was not the default installation.
Set up a Python3.8 environment with: conda activate d:\Users\dougj\Python3_8\
Install openseespy then ospgrillage with pip
Create an ospgrillage folder and a Condaenv.bat file to activate the environment.

The example grillage then ran without a problem.

For the benefit of others I suggest:
Correct the installation documentation to say that python 3.8 must be installed (not 3.8 or later).
Give detailed instructions for setting up both an environment for 3.8 using both virtualenv and condaenv.

**Comment by DougAJ4** [comment]
Also I was follow:ing the first example from the Examples section of the docs, but following the procedure given in Creating Grillage Models section, the command to create an I-beam member:
 I_beam = og.create_member(member_name="Intermediate I-beams", section=I_beam_section, material=concrete)
returns an error :
NameError: name 'I_beam_section' is not defined
(and concrete is also not yet defined)

**Comment by justinngan92** [comment]
The following section after the creation `I_beam` shows the definition of `I_beam_section` and `concrete` (these are the respective Section and Material objects of `I_beam`). You may need to put these definitions before `create_member()` function.

**Comment by ccaprani** [comment]
Hi @DougAJ4 did you get this sorted out?

**Comment by DougAJ4** [comment]
No, I have been distracted with other things (including SectionProperties,
which I see you are contributing to as well :))

But thanks for the reminder.

Doug

**Comment by ccaprani** [comment]
No worries @DougAJ4 - let me know how you go. By the way, as part of our Continuous Integration, we do test that a Python 3.9 install works on Windows, Mac, and Linux. Oh - and you might be interested in https://github.com/ccaprani/pycba

**Comment by ccaprani** [comment]
Hi @DougAJ4 ,
I'll close this now as a stale issue, but please do open another one if you have any further trouble. v0.3.1 is now released and available for pip install.
