### ISSUE TITLE
Help! Package not installing

### ISSUE THREAD

**Issue by abdelhaq-ourosama** [MonashSmartStructures/ospgrillage#94]
Hello, and thank you for sharing this. I'm new to scripting and modeling, but I want to streamline the bridge designs I create. It was a huge relief finding this package. However, I can't install it. It seems to require openseespyvis, but that package isn't available for installation. Could you please help me?

![image](https://github.com/MonashSmartStructures/ospgrillage/assets/153117082/8053eb32-d2db-4478-bc7a-712a9177e2e7)

PS : I'm using anaconda

**Comment by harsshh14** [comment]
I am facing the same issue. I needed ospgrillage to use in an open-source bridge design software that I am working on.

**Comment by abdelhaq-ourosama** [comment]
hello @harsshh14 ,
I managed to get it working. Here is what I did:

- Install a new environment in Anaconda with Python version 3.11 (the latest stable version then).
`conda create -n NewEnvName python=3.11`

- Install VFO.
`pip install vfo`

- Install ospgrillage directly from the Git repository, not from PyPI.
`pip install git+https://github.com/MonashSmartStructures/ospgrillage.git`

**Comment by ccaprani** [comment]
Thanks @abdelhaq-ourosama - #74 fixed this, but we haven't yet pushed an update to pypi.

@harsshh14 please try @abdelhaq-ourosama 's fix - it avoids pypi and installs directly from main.

**Comment by sarwashazl** [comment]
I had the same issue. I tried to fix it as @abdelhaq-ourosama says, but I got this error when trying to install:
pip install git+https://github.com/MonashSmartStructures/ospgrillage.git 

![image](https://github.com/user-attachments/assets/23589f1e-30a0-48f9-8891-52233008e3f0)

**Comment by jimstn** [comment]
Although v0.3.2 has been released, `pip install` still does not work for me, as v0.3.2 is not (yet) available on pip/PyPi - 
and pip attempts to install the latest version it is aware of (0.3.1) which has the broken dependency on `openseespyvis`

I looked in the closed issues before raising a new issue, and spotted @abdelhaq-ourosama 's advice to install ospgrillage directly from the Git repository... that works for me, thank you.

Someone may wish to reopen this issue, if it's not a quick fix to update PyPi?
