### ISSUE TITLE
Issue with "shell_beam" model type

### ISSUE THREAD

**Issue by abdelhaq-ourosama** [MonashSmartStructures/ospgrillage#98]
Hello @ccaprani @justinngan92 ,
Hope you're doing great.

There is an issue with "shell_beam" model type. I get this error when i run the workshop exemple "super-t_example-final.ipynb" and "Super-T_bridge_model_shell_beam.ipynb"
![image](https://github.com/user-attachments/assets/821288c3-a638-4fa9-a2e0-8d1c9d13c43f)

Note : there was an error with the `shell_model=og.create_grillage(...)` . I've added this argument  and it worked `mesh_type="orth",`

**Comment by ccaprani** [comment]
What version of `opsvis` do you have installed? Our requirements have `"opsvis~=0.95.5"` ([version spec](https://packaging.python.org/en/latest/specifications/version-specifiers/#id5)) and so if installed in its own `conda` or `venv` environemnt it should work fine.

**Comment by abdelhaq-ourosama** [comment]
Thanks for your promptness!

This is my version: opsvis==0.95.9

If I ignore the error and continue, the results at the end seem to be correct. I get the same moments when comparing the beam model with the shell_beam model. It looks like it's just a plotting error. Can you please confirm?

**Comment by justinngan92** [comment]
Hi @abdelhaq-ourosama, #107 should resolved the opsvis issue

**Comment by abdelhaq-ourosama** [comment]
Thanks @justinngan92 .
I'm getting another error. Here is what I did : 
- pip install --upgrade git+https://github.com/MonashSmartStructures/ospgrillage.git
- I've download the .ipynb of the workshop and run it.

First I've got an error with `create_grillage` so I had to add  `mesh_type="auto",` to make it work.
Next, I've got an error on the plotting line : `og.opsplt.plot_model("nodes");`


`Reading data from the nodes_ODB.
No directory found for nodes and elements
Reading node data from a OpenSees Tcl model
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\vfo\internal_database_functions.py:187, in _readNodesandElements(ModelName)
    186 try:
--> 187 	nodes = np.loadtxt(nodeFile, dtype, delimiter = delim, unpack=False)
    188 except:

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\npyio.py:1356, in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, quotechar, like)
   1354     delimiter = delimiter.decode('latin1')
-> 1356 arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
   1357             converters=converters, skiplines=skiprows, usecols=usecols,
   1358             unpack=unpack, ndmin=ndmin, encoding=encoding,
   1359             max_rows=max_rows, quote=quotechar)
   1361 return arr

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\npyio.py:975, in _read(fname, delimiter, comment, quote, imaginary_unit, usecols, skiplines, max_rows, converters, ndmin, unpack, dtype, encoding)
    974 if isinstance(fname, str):
--> 975     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    976     if encoding is None:

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\_datasource.py:193, in open(path, mode, destpath, encoding, newline)
    192 ds = DataSource(destpath)
--> 193 return ds.open(path, mode, encoding=encoding, newline=newline)

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\_datasource.py:533, in DataSource.open(self, path, mode, encoding, newline)
    532 else:
--> 533     raise FileNotFoundError(f"{path} not found.")

FileNotFoundError: nodes_ODB\Nodes.out not found.

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\vfo\vfo.py:462, in plot_model(model, show_nodes, show_nodetags, show_eletags, font_size, setview, elementgroups, line_width, filename)
    461 try:
--> 462 	this_nodeArray, elementArray, eleClassTags = idbf._readNodesandElements(model) ## Add eleClassTags to the Tcl data
    463 	# print(np.shape(nodeArray))

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\vfo\internal_database_functions.py:190, in _readNodesandElements(ModelName)
    189 	print("Reading node data from a OpenSees Tcl model")
--> 190 	nodes = np.transpose(np.loadtxt(nodeFile, dtype=float, delimiter=None, converters=None, unpack=True))
    192 # Populate an array with the input element information

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\npyio.py:1356, in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows, quotechar, like)
   1354     delimiter = delimiter.decode('latin1')
-> 1356 arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
   1357             converters=converters, skiplines=skiprows, usecols=usecols,
   1358             unpack=unpack, ndmin=ndmin, encoding=encoding,
   1359             max_rows=max_rows, quote=quotechar)
   1361 return arr

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\npyio.py:975, in _read(fname, delimiter, comment, quote, imaginary_unit, usecols, skiplines, max_rows, converters, ndmin, unpack, dtype, encoding)
    974 if isinstance(fname, str):
--> 975     fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    976     if encoding is None:

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\_datasource.py:193, in open(path, mode, destpath, encoding, newline)
    192 ds = DataSource(destpath)
--> 193 return ds.open(path, mode, encoding=encoding, newline=newline)

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\numpy\lib\_datasource.py:533, in DataSource.open(self, path, mode, encoding, newline)
    532 else:
--> 533     raise FileNotFoundError(f"{path} not found.")

FileNotFoundError: nodes_ODB\Nodes.out not found.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[69], line 1
----> 1 og.opsplt.plot_model("nodes")

File ~\anaconda3\envs\anaconda_py311\Lib\site-packages\vfo\vfo.py:465, in plot_model(model, show_nodes, show_nodetags, show_eletags, font_size, setview, elementgroups, line_width, filename)
    463 		# print(np.shape(nodeArray))
    464 	except:
--> 465 		raise Exception(">>>> VFO ERROR: No Model_ODB found. Exiting 'plot_model()' function now.<<<<")
    467 # print("this_nodeArray", this_nodeArray)
    468 # print("shape this_nodeArray", np.shape(this_nodeArray))
    469 # print("elementArray", elementArray)
    470 # print("eleClassTags", eleClassTags)
    471 
    472 ## Check if the model is 2D or 3D
    473 nodeArray = np.zeros([len(this_nodeArray[:,0]), 4])

Exception: >>>> VFO ERROR: No Model_ODB found. Exiting 'plot_model()' function now.<<<<`

**Comment by abdelhaq-ourosama** [comment]
I also try this : 
`og.opsplt.plot_model(show_nodes="yes",show_nodetags="yes")  # plotting using vfo
og.opsv.plot_model(az_el=(-90, 0))  # plotting using ops_vis
og.plt.show()`

I got the same error as the one at the source of the curent issue with this in addition : 
No Model_ODB specified, trying to get data from the active model.
Error displaying widget
A view with name (P_0x21413047b50_1) is already registered
 => returning previous one
Error displaying widget
